# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download PDCurses
        run: |
          curl -L -o D:/PDCurses.zip https://sourceforge.net/projects/pdcurses/files/latest/download
          mkdir D:/PDCurses
          cd D:/PDCurses
          unzip D:/PDCurses.zip
        shell: bash

      - name: Build PDCurses
        id: build
        run: |
          make -f Makefile WIDE=Y UTF8=Y DLL=Y
          echo "::set-output name=status::success"
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@master
        if: steps.build.outputs.status == 'success'
        with:
          name: PDCurses
          path: D:\PDCurses
